/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:588233d6-cb2f-47ca-b798-fab1fe168e59",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_43CHEeHrf",
    "aws_user_pools_web_client_id": "17vlp8euerhgqp5kbnnc3r3n9a",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://avdaavmvljdlxgbogzt5q4i2ei.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-d2mdqha77vfkhd62q7l23audji",
    "aws_user_files_s3_bucket": "amplifyreactgraphqlbucket210634-staging",
    "aws_user_files_s3_bucket_region": "eu-west-1"
};


export default awsmobile;
